### ISSUE TITLE
Frida - Finding libil2cpp.so

### ISSUE THREAD

**Issue by ssngoh** [Egoistically/SINoALICE#1]
Hey, may I know how are you able to retrieve the address for libil2cpp.so using frida?

I've tried searching around and playing with the API but it keeps returning null. The snippet of code I am using is this
function awaitForCondition(callback) {
    var i = setInterval(function () 
    {
      var addr = Module.findBaseAddress('libil2cpp.so');
        console.log("Address found:", addr);
        if (addr) 
        {
            clearInterval(i);
            callback(+addr);
        }
    }, 0.5);
}

I used frida -U -f com.nexon.sinoalice --no-pause -l scriptname.js to execute the app from the start, but I am still getting null for the address of libil2cpp.so

I've also tried Module.findExportByName(null, "dlopen") using an interceptor, but it seems to always crash after
dlopen called with: /system/lib64/hw/gralloc.goldfish.so
Process crashed: Bad access due to invalid address

Any help would be appreciated thanks!

**Comment by Egoistically** [comment]
Oof sorry for the late response, I do use the exact same code to get the base address so it's pretty weird you're getting null.

Here's a snippet of the code I use:
```javascript
function awaitForCondition(callback) {
    var i = setInterval(function () {
        var addr = Module.findBaseAddress("libil2cpp.so");
        console.log("Adress: ", addr);
        if (addr) {
            clearInterval(i);
            callback(+addr);
        }
    }, 0);
}

var il2cpp = null;

Java.perform(function() {
    awaitForCondition(function (base) {
        il2cpp = ptr(base);
        intercept();
    })
})

function intercept() {
    var inter = il2cpp.add("0x147F014");

    Interceptor.attach(inter, {
        onEnter: function(args) {
            console.log('onEnter');
        },
        onLeave: function(retval) {
            //
        }
    });
};
```

**Comment by isaacngoh1989** [comment]
Thanks for the reply! 
I found out that the reason I am getting null could be because I am using a rooted bluestacks instead of an actual phone. (Didn't really want to root my phone, so I went to root the emulator instead)

May I know if you are using an emulator or a rooted phone?

**Comment by ssngoh** [comment]
Thanks for the reply!
I found out that the reason I am getting null could be because I am using a rooted bluestacks instead of an actual phone. (Didn't really want to root my phone, so I went to root the emulator instead)

May I know if you are using an emulator or a rooted phone?

**Comment by Egoistically** [comment]
An old rooted phone of mine, tried using BlueStacks as well for ease of use but after multiple hours tinkering I couldn't get it working. 
Although it must be said that was over half a year ago, so the situation might've changed.

As a side note, if you want a smoother communication we can talk on Discord, my id is on the README.
